### PR TITLE
use class alias instead of extends

### PR DESCRIPTION
**Pull request by keywan-ghadami-oxid**
seam to be more correct for me to use class_alias because shop does it also this way.

### CODE REVIEW

**Comment by robertblank** [comment]
In PHPStorm, your PR improves the current solution, because PHPStorm jumps directly to the proper class and not to the ide helper file :-)
Do you know, if other IDEs are able to use class_alias() for auto completion (NetBeans, Eclipse PDT)?

**Comment by keywan-ghadami-oxid** [comment]
Netbeans shoulb be able to understand class_alias from v8.0.1 (https://netbeans.org/bugzilla/show_bug.cgi?id=243271)

**Comment by robertblank** [comment]
Hi Keywan,
The link you provided does not talk about the build in PHP function class_alias(), but about a class alias in a "use" statement.
I did a short check with NetBeans 8.2 and it seems that your PR breaks the autocompletion at least in the default setup of NetBeans.
Maybe there is a way to please all mayor IDEs (write 2 files, one general and one specially for PHPStorm), but as it is your PR is no improvement for NetBeans users.
I will close this PR now.

**Comment by keywan-ghadami-oxid** [comment]
sorry i was looking at wrong bug report, thats the correct one and it's still open :-(
https://netbeans.org/bugzilla/show_bug.cgi?id=214344
so you are right - we will have to wait...

**Pull request closed without merging**
